version: 2.1
  orbs:
    sfdx: circleci/salesforce-sfdx@2.1
  jobs:
    create-open-delete:
      executor: sfdx/default
      steps:
        - checkout
        - sfdx/install
        - sfdx/auth:
            defaultusername: user@email.com
        - sfdx/scratch-create:
            scratch-alias: circleci
            scratch-config: ./config/project-scratch-def.json
        - sfdx/scratch-open:
            scratch-alias: circleci
        - sfdx/scratch-delete:
            scratch-alias: circleci
  workflows:
    basic-test:
      jobs:
        - create-open-delete