jobs:
  create-open-delete:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - run:
          command: echo "sfdx force：auth：logout --u toyo_aki@si.com"
          name: コマンド実行
      - sfdx/auth:
          defaultusername: toyo_aki@si.com
      - sfdx/scratch-create:
          scratch-alias: circleci
          scratch-config: ./config/project-scratch-def.json
      - sfdx/scratch-open:
          scratch-alias: circleci
      - sfdx/scratch-delete:
          scratch-alias: circleci
orbs:
  sfdx: circleci/salesforce-sfdx@2.1
version: 2.1
workflows:
  basic-test:
    jobs:
      - create-open-delete
